---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-flask-deployement
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 2
  # Pod template
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: smoualouks/projet1:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mariadb # correspond au nom donné (metadata.name) donné au svc/mariadb
            - name: SAVE_DB
              value: "True"
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: azerty
            - name: DB_NAME
              value: projet1
---
kind: Service
apiVersion: v1
metadata:
  name: flaskapp # utilisé en résolution DNS
spec:
  type: NodePort # connectivité externe/interne
  selector:
    app: flaskapp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
